build:
  excludeCorrectable: true
  maxIssues: 10

comments:
  CommentOverPrivateFunction:
    active: false
  CommentOverPrivateProperty:
    active: false

complexity:
  LargeClass:
    active: true
    threshold: 500
  LongMethod:
    active: true
    threshold: 40
    ignoreAnnotated: [ 'Composable' ]
  LongParameterList:
    active: true
    functionThreshold: 10
    constructorThreshold: 15
    ignoreDefaultParameters: true
    ignoreDataClasses: true
    ignoreAnnotated: [ 'Composable' ]
  MethodOverloading:
    active: false
  NestedBlockDepth:
    active: true
    threshold: 3
    ignoreAnnotated: [ 'Composable' ]
  StringLiteralDuplication:
    active: true
    threshold: 2
    ignoreAnnotation: true
    excludeStringsWithLessThan5Characters: true
    ignoreStringsRegex: '$^'
  TooManyFunctions:
    active: true
    thresholdInFiles: 25
    thresholdInClasses: 25
    thresholdInInterfaces: 10
    thresholdInObjects: 10
    thresholdInEnums: 3

exceptions:
  ExceptionRaisedInUnexpectedLocation:
    active: true
  NotImplementedDeclaration:
    active: true
  TooGenericExceptionCaught:
    active: false
  PrintStackTrace:
    active: true

formatting:
  android: true
  EnumEntryNameCase:
    active: true
  ImportOrdering:
    active: true
  Indentation:
    active: true
  NoWildcardImports:
    active: false
  Filename:
    active: false

naming:
  BooleanPropertyNaming:
    active: true
  EnumNaming:
    active: true
    enumEntryPattern: '^(?:[A-Z]+[a-z0-9]+)[A-Za-z0-9]*$'
  FunctionNaming:
    active: true
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
  ObjectPropertyNaming:
    active: true
    constantPattern: '^(?:[A-Z]+[a-z0-9]+)[A-Za-z0-9]*$'
    propertyPattern: '^(?:[A-Z]+[a-z0-9]+)[A-Za-z0-9]*$'
  TopLevelPropertyNaming:
    active: true
    constantPattern: '^(?:[A-Z]+[a-z0-9]+)[A-Za-z0-9]*$'
    propertyPattern: '^(?:[A-Z]+[a-z0-9]+)[A-Za-z0-9]*$'

potential-bugs:
  ImplicitDefaultLocale:
    active: true
  MapGetWithNotNullAssertionOperator:
    active: true
  UnnecessaryNotNullOperator:
    active: true
  UnnecessarySafeCall:
    active: true
  UnsafeCast:
    active: true

style:
  ForbiddenMethodCall:
    active: true
    methods:
      - 'kotlin.io.println'
      - 'kotlin.io.print'
  MandatoryBracesIfStatements:
    active: true
  MandatoryBracesLoops:
    active: true
  SpacingBetweenPackageAndImports:
    active: true
  TrailingWhitespace:
    active: true
  UnderscoresInNumericLiterals:
    active: true
  UnusedImports:
    active: true
  UnusedPrivateMember:
    active: true
    ignoreAnnotated: [ 'Preview' ]
  UseDataClass:
    active: true
    allowVars: true
  VarCouldBeVal:
    active: true
  WildcardImport:
    active: false
  ForbiddenComment:
    values: [ 'STOPSHIP:', 'stopship:', 'STOPSHIP', 'stopship' ]
  ReturnCount:
    active: true
    excludeGuardClauses: true
  MagicNumber:
    active: true
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotated: [ 'Preview', 'Composable' ]
  SerialVersionUIDInSerializableClass:
    active: false
  MaxLineLength:
    excludeCommentStatements: true

TwitterCompose:
  CompositionLocalAllowlist:
    active: false
  CompositionLocalNaming:
    active: true
  ContentEmitterReturningValues:
    active: true
  ModifierComposable:
    active: true
  ModifierMissing:
    active: true
  ModifierReused:
    active: true
  ModifierWithoutDefault:
    active: true
  MultipleEmitters:
    active: true
  MutableParams:
    active: true
  ComposableNaming:
    active: true
  ComposableParamOrder:
    active: true
  PreviewNaming:
    active: true
  PreviewPublic:
    active: false
  RememberMissing:
    active: true
  UnstableCollections:
    active: true
  ViewModelForwarding:
    active: true
  ViewModelInjection:
    active: true
