build:
  excludeCorrectable: true

comments:
  CommentOverPrivateFunction:
    active: true
  CommentOverPrivateProperty:
    active: true
  UndocumentedPublicClass:
    active: true
    searchInNestedClass: true
    searchInInnerClass: false
    searchInInnerObject: false
    searchInInnerInterface: false
    excludes: ['**/model/**']

complexity:
  LargeClass:
    active: true
    threshold: 500
  LongMethod:
    active: true
    threshold: 40
  LongParameterList:
    active: true
    functionThreshold: 5
    constructorThreshold: 8
    ignoreDefaultParameters: true
    ignoreDataClasses: true
  MethodOverloading:
    active: true
    threshold: 3
  NestedBlockDepth:
    active: true
    threshold: 3
  StringLiteralDuplication:
    active: true
    threshold: 2
    ignoreAnnotation: true
    excludeStringsWithLessThan5Characters: true
    ignoreStringsRegex: '$^'
  TooManyFunctions:
    active: true
    thresholdInFiles: 20
    thresholdInClasses: 15
    thresholdInInterfaces: 10
    thresholdInObjects: 10
    thresholdInEnums: 3

exceptions:
  ExceptionRaisedInUnexpectedLocation:
    active: true
  NotImplementedDeclaration:
    active: true
  PrintStackTrace:
    active: true

formatting:
  android: true
  EnumEntryNameCase:
    active: true
  ImportOrdering:
    active: true
  Indentation:
    active: true

naming:
  EnumNaming:
    active: true
    enumEntryPattern: '[A-Z][_A-Z0-9]*'

potential-bugs:
  ImplicitDefaultLocale:
    active: true
  LateinitUsage:
    active: true
  MapGetWithNotNullAssertionOperator:
    active: true
  UnnecessaryNotNullOperator:
    active: true
  UnnecessarySafeCall:
    active: true
  UnsafeCast:
    active: true

style:
  ForbiddenMethodCall:
    active: true
    methods:
      - 'kotlin.io.println'
      - 'kotlin.io.print'
      - 'android.util.Log.wtf'
      - 'android.util.Log.e'
      - 'android.util.Log.w'
      - 'android.util.Log.d'
      - 'android.util.Log.i'
      - 'android.util.Log.v'
  MandatoryBracesIfStatements:
    active: true
  MandatoryBracesLoops:
    active: true
  SpacingBetweenPackageAndImports:
    active: true
  TrailingWhitespace:
    active: true
  UnderscoresInNumericLiterals:
    active: true
  UnusedImports:
    active: true
  UnusedPrivateMember:
    active: true
  UseDataClass:
    active: true
    allowVars: true
  UnnecessaryAbstractClass:
    active: false
  VarCouldBeVal:
    active: true
  WildcardImport:
    active: false
  ForbiddenComment:
    values: ['STOPSHIP:']
